# Generated by Django 5.2.15 on 2026-06-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="nota_media",
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota1",
            field=models.CharField(
                default="N/A", max_length=5, verbose_name="Nota 1º Bimestre"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota2",
            field=models.CharField(
                default="N/A", max_length=5, verbose_name="Nota 2º Bimestre"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota3",
            field=models.CharField(
                default="N/A", max_length=5, verbose_name="Nota 3º Bimestre"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota4",
            field=models.CharField(
                default="N/A", max_length=5, verbose_name="Nota 4º Bimestre"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota5",
            field=models.CharField(
                default="N/A", max_length=5, verbose_name="Nota 5º Bimestre"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota6",
            field=models.CharField(
                default="N/A", max_length=5, verbose_name="Nota 6º Bimestre"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
